config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/chbrandt/sqaaas-assessment:
      branch: main
      repo: https://github.com/chbrandt/sqaaas-assessment
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/chbrandt/sqaaas-assessment git:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-yellow-cichlid.sh
        container: qc.acc_bumpy-plum-mammoth
  QC.Doc:
    repos:
      github.com/chbrandt/sqaaas-assessment find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-denim-toucan.sh
        container: qc.doc_squeaky-burgundy-hare
      github.com/chbrandt/sqaaas-assessment git:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-gold-newt.sh
        container: qc.doc_snoopy-amber-spoonbill
      github.com/chbrandt/sqaaas-assessment markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-coral-jaguar.sh
        container: qc.doc_smelly-lilac-macaw
  QC.Lic:
    repos:
      github.com/chbrandt/sqaaas-assessment licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-copper-kakapo.sh
        container: qc.lic_frumpy-viridian-chicken
  QC.Sec:
    repos:
      github.com/chbrandt/sqaaas-assessment bandit:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-cinnamon-monster.sh
        container: qc.sec_craggy-carmine-insect
  QC.Sty:
    repos:
      github.com/chbrandt/sqaaas-assessment flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-persimmon-cuscus.sh
        container: qc.sty_jumpy-lime-anteater
  QC.Uni:
    repos:
      github.com/chbrandt/sqaaas-assessment pytest:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-tangerine-gorilla.sh
        container: qc.uni_beady-alizarin-audemer
  QC.Ver:
    repos:
      github.com/chbrandt/sqaaas-assessment get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-orchid-angora.sh
        container: qc.ver_cranky-wisteria-bat
timeout: 5400
