config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/chbrandt/sqaaas-assessment:
      branch: main
      repo: https://github.com/chbrandt/sqaaas-assessment
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/chbrandt/sqaaas-assessment git:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-dandelion-devil.sh
        container: qc.acc_muzzy-ivory-capybara
  QC.Doc:
    repos:
      github.com/chbrandt/sqaaas-assessment find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-crimson-wolverine.sh
        container: qc.doc_cloudy-amaranth-kingfisher
      github.com/chbrandt/sqaaas-assessment git:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-amber-dachshund.sh
        container: qc.doc_scaly-blue-wolverine
      github.com/chbrandt/sqaaas-assessment markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-aqua-rottweiler.sh
        container: qc.doc_shabby-viridian-mau
  QC.Lic:
    repos:
      github.com/chbrandt/sqaaas-assessment licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-lemon-barnacle.sh
        container: qc.lic_pretty-scarlet-indri
  QC.Sec:
    repos:
      github.com/chbrandt/sqaaas-assessment bandit:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-apricot-lemming.sh
        container: qc.sec_slaphappy-smalt-barb
  QC.Sty:
    repos:
      github.com/chbrandt/sqaaas-assessment flake8:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-heliotrope-chinchilla.sh
        container: qc.sty_frumpy-wheat-booby
  QC.Uni:
    repos:
      github.com/chbrandt/sqaaas-assessment pytest:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-auburn-woodlouse.sh
        container: qc.uni_lovely-taupe-tzu
  QC.Ver:
    repos:
      github.com/chbrandt/sqaaas-assessment get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-puce-dhole.sh
        container: qc.ver_chewy-xanthic-tetra
timeout: 5400
